### ISSUE TITLE
Provide alignedFree counterpart to alignedAlloc

### ISSUE THREAD

**Issue by kaoskorobase** [samplecount/methcla#97]
Some aligned malloc implementations don't work with the standard free function. Provide an additional function in `Methcla::Memory` and use it where appropriate.

**Comment by kaoskorobase** [comment]
We use `_aligned_malloc` on MinGW now, should be using `_aligned_free` for freeing that memory.

**Comment by kaoskorobase** [comment]
Here's an example stack trace:

```
warning: HEAP[methcla-tests.exe]:
warning: Invalid address specified to RtlFreeHeap( 00B60000, 02210050 )

Program received signal SIGTRAP, Trace/breakpoint trap.
0x77f21757 in ?? ()
(gdb) where
#0  0x77f21757 in ?? ()
#1  0x77f20671 in ?? ()
#2  0x77ed8033 in ?? ()
#3  0x77e7ff39 in ?? ()
#4  0x75be9a15 in msvcrt!free () from C:\Windows\SysWOW64\msvcrt.dll
#5  0x00b60000 in ?? ()
#6  0x0040f957 in Methcla::Memory::free (ptr=0x2210050)
    at .\src/Methcla/Memory.cpp:59
#7  0x004452ac in Methcla::Audio::MultiChannelBuffer::freeBuffers (
    numChannels=2, buffers=0xb66898)
    at src/Methcla/Audio/MultiChannelBuffer.hpp:114
#8  0x00445660 in Methcla::Audio::IO::Driver::freeBuffers (numChannels=2,
    buffers=0xb66898) at src/Methcla/Audio/IO/Driver.hpp:67
#9  0x00411c4a in Methcla::Audio::IO::DummyDriver::~DummyDriver (
    this=0xb66648, __in_chrg=<optimized out>)
    at src/Methcla/Audio/IO/DummyDriver.cpp:47
#10 0x00411ca3 in Methcla::Audio::IO::DummyDriver::~DummyDriver (
    this=0xb66648, __in_chrg=<optimized out>)
    at src/Methcla/Audio/IO/DummyDriver.cpp:49
#11 0x0043da87 in Methcla_AudioDriver::~Methcla_AudioDriver (this=0xb666b8,
    __in_chrg=<optimized out>) at src/Methcla/API.cpp:45
#12 0x0045df3c in std::default_delete<Methcla_AudioDriver>::operator() (
    this=0xb666dc, __ptr=0xb666b8)
    at c:/mingw/msys/1.0/opt/windows_32/include/c++/4.8.2/bits/unique_ptr.h:67
#13 0x00465886 in std::unique_ptr<Methcla_AudioDriver, std::default_delete<Methc
la_AudioDriver> >::~unique_ptr (this=0xb666dc, __in_chrg=<optimized out>)
    at c:/mingw/msys/1.0/opt/windows_32/include/c++/4.8.2/bits/unique_ptr.h:184
#14 0x0043d933 in _fu156___ZNSt12placeholders2_1E () at src/Methcla/API.cpp:98
#15 0x00410999 in methcla_engine_new_with_driver (options=0x28fa94,
    driver=0xb666b8, engine=0xb664e4) at src/Methcla/API.cpp:243
#16 0x00446eda in Methcla::Engine::Engine (this=0xb664e0, inOptions=...,
    driver=0xb666b8) at include/methcla/engine.hpp:857
#17 0x0041535f in Methcla_Engine_Freeing_invalid_node_id_should_not_crash_Test::
TestBody (this=0xb65460) at tests/methcla_engine_tests.cpp:40
#18 0x00456fcd in testing::internal::HandleSehExceptionsInMethodIfSupported<test
ing::Test, void> (object=0xb65460,
    method=&virtual testing::Test::TestBody(),
    location=0x488227 <testing::internal::kStackTraceMarker+1750> "the test body
") at external_libraries/gtest/gtest-all.cc:3562
#19 0x00456a57 in testing::internal::HandleExceptionsInMethodIfSupported<testing
::Test, void> (object=0xb65460, method=&virtual testing::Test::TestBody(),
    location=0x488227 <testing::internal::kStackTraceMarker+1750> "the test body
") at external_libraries/gtest/gtest-all.cc:3598
#20 0x0041fb00 in testing::Test::Run (this=0xb65460)
    at external_libraries/gtest/gtest-all.cc:3635
#21 0x004203a9 in testing::TestInfo::Run (this=0xb62f98)
    at external_libraries/gtest/gtest-all.cc:3810
#22 0x00420a62 in testing::TestCase::Run (this=0xb62d58)
    at external_libraries/gtest/gtest-all.cc:3928
#23 0x00427c41 in testing::internal::UnitTestImpl::RunAllTests (this=0xb62bd8)
    at external_libraries/gtest/gtest-all.cc:5799
#24 0x00456f55 in testing::internal::HandleSehExceptionsInMethodIfSupported<test
ing::internal::UnitTestImpl, bool> (object=0xb62bd8,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTes
tImpl * const)) 0x427960 <testing::internal::UnitTestImpl::RunAllTests()>,
    location=0x488b20 <testing::internal::OsStackTraceGetter::kElidedFramesMarke
r+64> "auxiliary test code (environments or event listeners)")
    at external_libraries/gtest/gtest-all.cc:3562
#25 0x00456587 in testing::internal::HandleExceptionsInMethodIfSupported<testing
::internal::UnitTestImpl, bool> (object=0xb62bd8,
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTes
tImpl * const)) 0x427960 <testing::internal::UnitTestImpl::RunAllTests()>,
    location=0x488b20 <testing::internal::OsStackTraceGetter::kElidedFramesMarke
r+64> "auxiliary test code (environments or event listeners)")
    at external_libraries/gtest/gtest-all.cc:3598
#26 0x00426958 in testing::UnitTest::Run (
    this=0x491144 <testing::UnitTest::GetInstance()::instance>)
    at external_libraries/gtest/gtest-all.cc:5413
#27 0x0043d43a in RUN_ALL_TESTS () at external_libraries/gtest/gtest.h:20058
#28 0x00418c6d in main (argc=1, argv=0xb62918)
    at tests/test_runner_console.cpp:22
```

**Comment by kaoskorobase** [comment]
An important thing to note is that this change would also affect the public plugin API. Maybe it would be best not to expose the aligned allocation functions and only guarantee SIMD alignment for all memory allocated from the heap?
